name: Notify on Change

on:
  push:
    branches:
      - '**'  # Monitor all branches
  pull_request:
    branches:
      - '**'  # Monitor all branches

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all branches

    - name: Get total file count in all branches
      id: file_count
      run: |
        total_files=$(git ls-tree -r --name-only HEAD | wc -l)
        echo "::set-output name=total_files::$total_files"

    - name: Get commit details
      id: commit_details
      run: |
        echo "::set-output name=message::$(git log -1 --pretty=%B)"
        echo "::set-output name=sha::$(git log -1 --pretty=%H)"
        echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"

    - name: Send notification email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.office365.com  # Replace with your SMTP server
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: Repository Change Notification
        to: athulya.s@netcon.in  # Replace with the recipient's email address
        from: netconncmp@netcon.in  # Replace with the sender's email address
        body: |
          Changes have been made to the repository.
          Branch: ${{ steps.commit_details.outputs.branch }}
          Total number of files: ${{ steps.file_count.outputs.total_files }}
          Commit details:
          Message: ${{ steps.commit_details.outputs.message }}
          URL: https://github.com/${{ github.repository }}/commit/${{ steps.commit_details.outputs.sha }}
