name: Notify on Change

on:
  push:
    branches:
      - '**'  # Monitor all branches
  pull_request:
    branches:
      - '**'  # Monitor all branches

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all branches

    - name: Get all branches
      id: branches
      run: |
        branches=$(git branch -r | grep -v '\->' | sed 's/origin\///')
        echo "branches=$(echo $branches | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Count script files in all branches
      id: file_count
      run: |
        total_files=0
        branches=$(git branch -r | grep -v '\->' | sed 's/origin\///')
        for branch in $branches; do
          git checkout $branch
          branch_files=$(git ls-tree -r --name-only HEAD | grep -E '\.sh$|\.py$|\.js$|\.ps1$|\.xaml$|\.yml$|\.xml$|\.yaml$' | wc -l)
          total_files=$((total_files + branch_files))
        done
        echo "total_files=$total_files" >> $GITHUB_ENV

    - name: Count total files excluding specific extensions
      id: total_file_count
      run: |
        total_files=0
        for branch in ${{ env.branches }}; do
          git checkout $branch
          branch_files=$(git ls-tree -r --name-only HEAD | grep -vE '\.jpg$|\.JPG$|\.txt$|\.md$|\.ppt$' | wc -l)
          total_files=$((total_files + branch_files))
        done
        echo "total_files_excluding=$total_files" >> $GITHUB_ENV

    - name: Get commit details
      id: commit_details
      run: |
        echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
        echo "sha=$(git log -1 --pretty=%H)" >> $GITHUB_ENV
        echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
    - name: Send notification email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.office365.com  # Replace with your SMTP server
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: Repository Change Notification
        to: athulya.s@netcon.in  # Replace with the recipient's email address
        from: netconncmp@netcon.in  # Replace with the sender's email address
        body: |
          Changes have been made to the repository.
          Branch: ${{ env.branch }}
          Total number of script files: ${{ env.total_files }}
          Total number of files excluding specific extensions: ${{ env.total_files_excluding }}
          Commit details:
          Message: ${{ env.message }}
          URL: https://github.com/${{ github.repository }}/commit/${{ env.sha }}
